version: '3'
services:
  app:
    network_mode: "host"
    privileged: true
    cap_add:
    - SYS_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /lib/modules:/lib/modules:ro   
    - /usr/src:/usr/src:ro   
    - /etc/localtime:/etc/localtime